"""add new column to see if course is active or not

Revision ID: bcbf754013eb
Revises: 005
Create Date: 2026-08-23 11:06:26.303524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, Sequence[str], None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), nullable=False,server_default=sa.true()))
    op.add_column('lessons', sa.Column('is_active', sa.Boolean(), nullable=False,server_default=sa.true()))
    op.add_column('materials', sa.Column('is_active', sa.Boolean(), nullable=False,server_default=sa.true()))
    op.add_column('units', sa.Column('is_active', sa.Boolean(), nullable=False,server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('units', 'is_active')
    op.drop_column('materials', 'is_active')
    op.drop_column('lessons', 'is_active')
    op.drop_column('courses', 'is_active')
    # ### end Alembic commands ###
